### ISSUE TITLE
Failed running multiple instances of qemu with pok (with qemu 3.0.0)

### ISSUE THREAD

**Issue by Etienne13** [pok-kernel/pok#14]
When I run several instances of qemu with pok, I get the following error:

`qemu-system-i386: Initialization of device isa-fdc failed: Failed to get "write" lock
Is another process using the image?`

Notes:
 - it is reproducible using the network example (which launches 2 qemu) and qemu 3.0.0
 - the problem does not occur with qemu 2.5.0

**Comment by juli1** [comment]
sounds like a problem with qemu and/or how we handle qemu - did you check for such issues on the qemu bugtrack system?

**Comment by Etienne13** [comment]
Just found this: https://bugzilla.redhat.com/show_bug.cgi?id=1543285
it indicates qemu developers won't fix it and they recommend we use a different image per qemu VM.

**Comment by Etienne13** [comment]
I agree; I think the destination of the copy could be specified with a variable in the makefile (not to make it too random ;))

**Comment by juli1** [comment]
that would make it platform-dependent and requires change to the code generator.

**Comment by Etienne13** [comment]
Not sure what you mean by this; what would be your recommendation?

Here is what I did on my end as a test:
1. In config.mk (generated by misc/conf-env.pl) I changed the value of CONFIG_QEMU_x86: 

`CONFIG_QEMU_x86= -fda grub-boot-only.img`

2. In grub-floppy.mk I inserted before the launch of qemu (in launch-run target):

`$(CP) $(POK_PATH)/misc/grub-boot-only.img ./`

It works on my end; would that be ok for you or do you want to investigate another solution on your end?

**Comment by Etienne13** [comment]
I just pushed a fix, which I tested on Linux. However, I expect to have broken things for windows and I cannot test it... Could you check if you can adapt the fix for Windows hosts?

**Comment by juli1** [comment]
It should be fine since the windows toolchain relies on cigwin.
