### ISSUE TITLE
Access to physical memory

### ISSUE THREAD

**Issue by megaloldean** [pok-kernel/pok#15]
How can I access physical memory?

**Comment by juli1** [comment]
Hi,

1. The issue tracker is to notify bugs, not questions.
2. Such questions can take many different angles, depending of the type of memory, architectures and so on.

And TL;DR: POK put all your partition in memory. Therefore, there is no "physical memory access" other than accessing partitions elements. If you think of device drivers, you can put exceptions to read registers, etc. Look at the network device driver in that case. Last, if you think of hard drive, this is not supported as of today (and POK was not designed for that).

So, again, not an issue but a question. Closing.
